In [53]:
import pandas as pd
import os

In [12]:
file = 'Resources/cbb.csv'
file1 = 'Resources/cbb13.csv'
file2 = 'Resources/cbb14.csv'
file3 = 'Resources/cbb15.csv'
file4 = 'Resources/cbb16.csv'
file5 = 'Resources/cbb17.csv'
file6 = 'Resources/cbb18.csv'
file7 = 'Resources/cbb19.csv'
file8 = 'Resources/cbb20.csv'
file9 = 'Resources/cbb21.csv'

In [38]:
df = pd.read_csv(file)
df2013 = pd.read_csv(file1)
df2014 = pd.read_csv(file2)
df2015 = pd.read_csv(file3)
df2016 = pd.read_csv(file4)
df2017 = pd.read_csv(file5)
df2018 = pd.read_csv(file6)
df2019 = pd.read_csv(file7)
df2020 = pd.read_csv(file8)
df2021 = pd.read_csv(file9)

df2021.head()

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,DRB,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED
0,Michigan,B10,24,20,118.1,91.1,0.9521,54.9,44.9,16.3,...,24.8,28.9,24.5,53.3,42.3,38.7,33.5,66.9,7.2,1.0
1,Baylor,B12,24,22,123.2,94.5,0.9548,57.5,49.1,17.6,...,30.9,27.0,31.7,54.1,48.1,41.8,34.0,68.8,6.6,1.0
2,Illinois,B10,29,23,117.7,90.4,0.9539,55.6,46.6,18.2,...,22.2,39.2,30.5,55.3,45.4,37.6,32.7,70.7,8.9,1.0
3,Gonzaga,WCC,26,26,125.4,89.8,0.9791,61.0,47.5,16.1,...,23.4,36.7,25.9,64.0,46.8,36.5,32.5,74.6,8.5,1.0
4,Iowa,B10,29,21,123.5,95.7,0.9491,54.6,48.3,13.3,...,28.6,32.0,22.6,52.4,45.8,38.6,34.8,70.0,5.6,2.0

In [18]:
df.sort_values(by=['YEAR'])

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
2454,Florida Gulf Coast,ASun,35,24,103.4,96.3,0.6952,51.6,46.9,21.0,...,32.7,52.3,46.9,33.4,31.3,69.1,-4.0,S16,15.0,2013
1932,Milwaukee,Horz,30,6,93.7,106.5,0.1871,44.6,50.5,21.5,...,30.2,43.5,51.1,30.8,32.7,65.9,-17.4,NaN,NaN,2013
1933,Hofstra,CAA,31,6,88.1,100.0,0.1890,42.0,48.9,22.2,...,36.7,41.6,50.0,28.7,31.0,64.9,-19.7,NaN,NaN,2013
1934,Longwood,BSth,31,6,93.5,114.2,0.0910,48.3,54.4,22.7,...,34.7,48.3,53.1,32.1,38.3,70.7,-19.5,NaN,NaN,2013
1935,SIU Edwardsville,OVC,25,7,90.4,106.4,0.1338,47.7,51.6,21.7,...,36.9,44.6,52.6,36.4,33.0,66.2,-13.8,NaN,NaN,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,Charlotte,CUSA,29,8,95.0,107.7,0.1916,48.1,51.3,22.0,...,32.6,49.2,49.9,31.1,35.5,65.9,-15.4,NaN,NaN,2019
530,William & Mary,CAA,30,14,102.3,107.0,0.3733,54.4,52.7,18.3,...,30.0,55.8,51.1,35.0,36.9,70.0,-11.1,NaN,NaN,2019
529,UNC Wilmington,CAA,32,10,103.8,113.0,0.2734,50.5,56.0,18.5,...,31.9,49.3,54.4,35.0,38.8,70.6,-16.7,NaN,NaN,2019
587,Marshall,CUSA,37,23,105.5,106.0,0.4860,51.9,52.0,15.9,...,32.4,52.3,51.4,34.2,35.5,75.7,-6.4,NaN,NaN,2019
592,UAB,CUSA,33,20,106.2,105.1,0.5307,50.4,49.4,16.8,...,31.6,51.3,48.1,32.6,33.9,66.4,-7.4,NaN,NaN,2019

In [39]:
df2020.insert(22, 'YEAR', 2020)
df2021.insert(22, 'YEAR', 2021)
df2021

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,SEED,YEAR
0,Michigan,B10,24,20,118.1,91.1,0.9521,54.9,44.9,16.3,...,28.9,24.5,53.3,42.3,38.7,33.5,66.9,7.2,1.0,2021
1,Baylor,B12,24,22,123.2,94.5,0.9548,57.5,49.1,17.6,...,27.0,31.7,54.1,48.1,41.8,34.0,68.8,6.6,1.0,2021
2,Illinois,B10,29,23,117.7,90.4,0.9539,55.6,46.6,18.2,...,39.2,30.5,55.3,45.4,37.6,32.7,70.7,8.9,1.0,2021
3,Gonzaga,WCC,26,26,125.4,89.8,0.9791,61.0,47.5,16.1,...,36.7,25.9,64.0,46.8,36.5,32.5,74.6,8.5,1.0,2021
4,Iowa,B10,29,21,123.5,95.7,0.9491,54.6,48.3,13.3,...,32.0,22.6,52.4,45.8,38.6,34.8,70.0,5.6,2.0,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,Louisiana Tech,CUSA,27,21,102.7,93.4,0.7479,50.5,45.6,18.4,...,35.3,26.4,49.7,46.4,34.6,29.6,69.6,-1.7,NaN,2021
343,Toledo,MAC,29,21,113.3,101.8,0.7743,54.3,48.3,15.5,...,28.5,23.4,52.5,51.0,37.7,29.5,69.1,-2.1,NaN,2021
344,UAB,CUSA,27,22,102.5,94.6,0.7153,48.6,47.0,15.6,...,29.9,27.1,49.4,46.1,31.1,32.4,67.5,-2.7,NaN,2021
345,Eastern Kentucky,OVC,27,22,101.5,102.3,0.4749,51.2,51.0,16.6,...,25.6,32.2,49.6,51.8,35.8,33.0,75.1,-3.8,NaN,2021
346,Belmont,OVC,29,26,108.5,101.6,0.6786,56.3,49.3,16.6,...,27.9,24.6,59.4,48.2,34.7,34.0,71.1,-1.1,NaN,2021

In [47]:
df20 = df2020.append([df2021])
display(df20)

,RK,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,YEAR,SEED
0,1.0,Kansas,B12,30,28,116.1,87.7,0.9616,53.7,43.7,...,35.8,23.2,54.9,42.4,34.1,30.5,67.4,10.8,2020,NaN
1,2.0,Baylor,B12,30,26,114.5,88.4,0.9513,49.4,45.2,...,30.8,30.8,47.5,44.4,35.1,31.1,66.2,8.5,2020,NaN
2,3.0,Gonzaga,WCC,33,31,121.3,94.3,0.9472,57.5,47.6,...,38.8,21.8,57.4,47.4,38.6,32.0,72.0,7.7,2020,NaN
3,4.0,Dayton,A10,31,29,119.5,93.4,0.9445,59.7,46.6,...,33.9,30.9,62.3,45.1,37.1,33.0,67.5,6.8,2020,NaN
4,5.0,Michigan St.,B10,31,22,114.8,91.3,0.9326,52.6,43.3,...,30.8,29.3,52.9,43.4,34.8,28.7,69.3,5.2,2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,NaN,Louisiana Tech,CUSA,27,21,102.7,93.4,0.7479,50.5,45.6,...,35.3,26.4,49.7,46.4,34.6,29.6,69.6,-1.7,2021,NaN
343,NaN,Toledo,MAC,29,21,113.3,101.8,0.7743,54.3,48.3,...,28.5,23.4,52.5,51.0,37.7,29.5,69.1,-2.1,2021,NaN
344,NaN,UAB,CUSA,27,22,102.5,94.6,0.7153,48.6,47.0,...,29.9,27.1,49.4,46.1,31.1,32.4,67.5,-2.7,2021,NaN
345,NaN,Eastern Kentucky,OVC,27,22,101.5,102.3,0.4749,51.2,51.0,...,25.6,32.2,49.6,51.8,35.8,33.0,75.1,-3.8,2021,NaN
346,NaN,Belmont,OVC,29,26,108.5,101.6,0.6786,56.3,49.3,...,27.9,24.6,59.4,48.2,34.7,34.0,71.1,-1.1,2021,NaN

In [49]:
df20.reset_index(drop=True)

,RK,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,...,FTR,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,YEAR,SEED
0,1.0,Kansas,B12,30,28,116.1,87.7,0.9616,53.7,43.7,...,35.8,23.2,54.9,42.4,34.1,30.5,67.4,10.8,2020,NaN
1,2.0,Baylor,B12,30,26,114.5,88.4,0.9513,49.4,45.2,...,30.8,30.8,47.5,44.4,35.1,31.1,66.2,8.5,2020,NaN
2,3.0,Gonzaga,WCC,33,31,121.3,94.3,0.9472,57.5,47.6,...,38.8,21.8,57.4,47.4,38.6,32.0,72.0,7.7,2020,NaN
3,4.0,Dayton,A10,31,29,119.5,93.4,0.9445,59.7,46.6,...,33.9,30.9,62.3,45.1,37.1,33.0,67.5,6.8,2020,NaN
4,5.0,Michigan St.,B10,31,22,114.8,91.3,0.9326,52.6,43.3,...,30.8,29.3,52.9,43.4,34.8,28.7,69.3,5.2,2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,NaN,Louisiana Tech,CUSA,27,21,102.7,93.4,0.7479,50.5,45.6,...,35.3,26.4,49.7,46.4,34.6,29.6,69.6,-1.7,2021,NaN
696,NaN,Toledo,MAC,29,21,113.3,101.8,0.7743,54.3,48.3,...,28.5,23.4,52.5,51.0,37.7,29.5,69.1,-2.1,2021,NaN
697,NaN,UAB,CUSA,27,22,102.5,94.6,0.7153,48.6,47.0,...,29.9,27.1,49.4,46.1,31.1,32.4,67.5,-2.7,2021,NaN
698,NaN,Eastern Kentucky,OVC,27,22,101.5,102.3,0.4749,51.2,51.0,...,25.6,32.2,49.6,51.8,35.8,33.0,75.1,-3.8,2021,NaN
699,NaN,Belmont,OVC,29,26,108.5,101.6,0.6786,56.3,49.3,...,27.9,24.6,59.4,48.2,34.7,34.0,71.1,-1.1,2021,NaN

In [50]:
df = df.append([df20])
display(df)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,RK
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016,NaN
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015,NaN
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018,NaN
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019,NaN
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,Louisiana Tech,CUSA,27,21,102.7,93.4,0.7479,50.5,45.6,18.4,...,49.7,46.4,34.6,29.6,69.6,-1.7,NaN,NaN,2021,NaN
343,Toledo,MAC,29,21,113.3,101.8,0.7743,54.3,48.3,15.5,...,52.5,51.0,37.7,29.5,69.1,-2.1,NaN,NaN,2021,NaN
344,UAB,CUSA,27,22,102.5,94.6,0.7153,48.6,47.0,15.6,...,49.4,46.1,31.1,32.4,67.5,-2.7,NaN,NaN,2021,NaN
345,Eastern Kentucky,OVC,27,22,101.5,102.3,0.4749,51.2,51.0,16.6,...,49.6,51.8,35.8,33.0,75.1,-3.8,NaN,NaN,2021,NaN
346,Belmont,OVC,29,26,108.5,101.6,0.6786,56.3,49.3,16.6,...,59.4,48.2,34.7,34.0,71.1,-1.1,NaN,NaN,2021,NaN

In [51]:
df.reset_index(drop=True)

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,RK
0,North Carolina,ACC,40,33,123.3,94.9,0.9531,52.6,48.1,15.4,...,53.9,44.6,32.7,36.2,71.7,8.6,2ND,1.0,2016,NaN
1,Wisconsin,B10,40,36,129.1,93.6,0.9758,54.8,47.7,12.4,...,54.8,44.7,36.5,37.5,59.3,11.3,2ND,1.0,2015,NaN
2,Michigan,B10,40,33,114.4,90.4,0.9375,53.9,47.7,14.0,...,54.7,46.8,35.2,33.2,65.9,6.9,2ND,3.0,2018,NaN
3,Texas Tech,B12,38,31,115.2,85.2,0.9696,53.5,43.0,17.7,...,52.8,41.9,36.5,29.7,67.5,7.0,2ND,3.0,2019,NaN
4,Gonzaga,WCC,39,37,117.8,86.3,0.9728,56.6,41.1,16.2,...,56.3,40.0,38.2,29.0,71.5,7.7,2ND,1.0,2017,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3150,Louisiana Tech,CUSA,27,21,102.7,93.4,0.7479,50.5,45.6,18.4,...,49.7,46.4,34.6,29.6,69.6,-1.7,NaN,NaN,2021,NaN
3151,Toledo,MAC,29,21,113.3,101.8,0.7743,54.3,48.3,15.5,...,52.5,51.0,37.7,29.5,69.1,-2.1,NaN,NaN,2021,NaN
3152,UAB,CUSA,27,22,102.5,94.6,0.7153,48.6,47.0,15.6,...,49.4,46.1,31.1,32.4,67.5,-2.7,NaN,NaN,2021,NaN
3153,Eastern Kentucky,OVC,27,22,101.5,102.3,0.4749,51.2,51.0,16.6,...,49.6,51.8,35.8,33.0,75.1,-3.8,NaN,NaN,2021,NaN
3154,Belmont,OVC,29,26,108.5,101.6,0.6786,56.3,49.3,16.6,...,59.4,48.2,34.7,34.0,71.1,-1.1,NaN,NaN,2021,NaN

In [52]:
df.sort_values(by=['YEAR'])

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR,RK
1822,Boston University,AE,30,17,103.2,101.1,0.5570,52.2,47.4,18.8,...,49.9,47.8,37.0,31.1,66.2,-6.9,NaN,NaN,2013,NaN
1934,Longwood,BSth,31,6,93.5,114.2,0.0910,48.3,54.4,22.7,...,48.3,53.1,32.1,38.3,70.7,-19.5,NaN,NaN,2013,NaN
1935,SIU Edwardsville,OVC,25,7,90.4,106.4,0.1338,47.7,51.6,21.7,...,44.6,52.6,36.4,33.0,66.2,-13.8,NaN,NaN,2013,NaN
1936,Tennessee Martin,OVC,28,7,91.9,112.9,0.0861,43.3,53.5,21.1,...,40.9,53.3,32.7,35.9,68.4,-16.0,NaN,NaN,2013,NaN
1937,Seattle,WAC,29,7,92.5,97.1,0.3642,47.1,46.7,25.5,...,46.5,45.9,32.2,32.1,70.1,-16.2,NaN,NaN,2013,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Loyola MD,Pat,17,6,97.7,100.9,0.4088,51.1,49.3,20.2,...,53.4,47.7,30.6,34.7,67.8,-8.7,NaN,NaN,2021,NaN
110,Cal St. Fullerton,BW,15,6,102.6,111.6,0.2758,51.2,54.9,17.6,...,48.1,52.5,38.0,39.7,71.7,-7.8,NaN,NaN,2021,NaN
109,Alabama A&M,SWAC,15,6,85.4,104.7,0.0878,44.8,44.0,21.4,...,45.5,44.8,28.8,28.3,67.4,-8.2,NaN,NaN,2021,NaN
117,Portland,WCC,18,6,97.6,112.2,0.1678,46.3,58.9,19.0,...,43.6,60.6,33.8,37.6,71.3,-9.4,NaN,NaN,2021,NaN
346,Belmont,OVC,29,26,108.5,101.6,0.6786,56.3,49.3,16.6,...,59.4,48.2,34.7,34.0,71.1,-1.1,NaN,NaN,2021,NaN

In [54]:
df.to_csv('Resources/cbb_combined.csv')